CONFIG_CURRENT_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CONFIG_CURRENT_DIR := $(dir $(CONFIG_CURRENT_PATH))
CONFIG_MODULE := ipc

LOCAL_$(CONFIG_MODULE)_INCLUDE :=
ifeq ($(OSZ_CFG_IPC), y)

LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/include

ifeq ($(OSZ_CFG_EVENT), y)
LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/include/event
endif

ifeq ($(OSZ_CFG_SEM), y)
LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/include/sem
endif

ifeq ($(OSZ_CFG_ATOMIC), y)
LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/include/atomic
endif

endif