set(OSZ_CFG_INIT y)
set(OSZ_CFG_HOOK y)
set(OSZ_CFG_DFX y)
set(OSZ_CFG_STARTUP y)
set(OSZ_CFG_STRUCT y)
set(OSZ_CFG_STRUCT_DLINK y)
set(OSZ_CFG_STRUCT_FIFO y)
set(OSZ_CFG_STRUCT_SORTLINK y)
set(OSZ_CFG_COMM y)
set(OSZ_CFG_MEM y)
set(OSZ_CFG_BESTFIT y)
set(OSZ_CFG_DEBUG y)
set(OSZ_CFG_TRAP y)
set(OSZ_CFG_EXCEPTION y)
set(OSZ_CFG_INTERRUPT y)
set(OSZ_CFG_RISCV y)
set(OSZ_CFG_STARTUP_STACK_SIZE 0x400)
set(OSZ_CFG_PRI_QUEUE_LIMIT 0x20)
set(OSZ_CFG_IPC y)
set(OSZ_CFG_SEM y)
set(OSZ_CFG_EVENT y)
set(OSZ_CFG_MUTEX y)
set(OSZ_CFG_ATOMIC y)
set(OSZ_CFG_SOFTTIMER y)
set(OSZ_CFG_SOFTTIMER_TASK_STACK 0x1000)
set(OSZ_CFG_SWT_MAX 0x20)
set(OSZ_CFG_TASK y)
set(OSZ_CFG_SCHEDULE y)
set(OSZ_CFG_PREEMPTION y)
set(OSZ_CFG_TASK_STACK_DEFAULT_SIZE 0x2000)
set(OSZ_CFG_INTERRUPT_STACK_SIZE 0x800)
set(OSZ_CFG_EXCEPTION_STACK_SIZE 0x800)
set(OSZ_CFG_DRIVERS y)
set(OSZ_CFG_UART y)
set(OSZ_CFG_TIMER y)
set(OSZ_CFG_TEST_SUITE y)
set(OSZ_CFG_TARGETS y)
set(OSZ_CFG_PLATFORM qemu_virt)
set(OSZ_CFG_SHELL y)

set(OSZ_CFG_MACRO 
OSZ_CFG_INIT=1
OSZ_CFG_HOOK=1
OSZ_CFG_DFX=1
OSZ_CFG_STARTUP=1
OSZ_CFG_STRUCT=1
OSZ_CFG_STRUCT_DLINK=1
OSZ_CFG_STRUCT_FIFO=1
OSZ_CFG_STRUCT_SORTLINK=1
OSZ_CFG_COMM=1
OSZ_CFG_MEM=1
OSZ_CFG_BESTFIT=1
OSZ_CFG_DEBUG=1
OSZ_CFG_TRAP=1
OSZ_CFG_EXCEPTION=1
OSZ_CFG_INTERRUPT=1
OSZ_CFG_RISCV=1
OSZ_CFG_STARTUP_STACK_SIZE=0x400
OSZ_CFG_PRI_QUEUE_LIMIT=0x20
OSZ_CFG_IPC=1
OSZ_CFG_SEM=1
OSZ_CFG_EVENT=1
OSZ_CFG_MUTEX=1
OSZ_CFG_ATOMIC=1
OSZ_CFG_SOFTTIMER=1
OSZ_CFG_SOFTTIMER_TASK_STACK=0x1000
OSZ_CFG_SWT_MAX=0x20
OSZ_CFG_TASK=1
OSZ_CFG_SCHEDULE=1
OSZ_CFG_PREEMPTION=1
OSZ_CFG_TASK_STACK_DEFAULT_SIZE=0x2000
OSZ_CFG_INTERRUPT_STACK_SIZE=0x800
OSZ_CFG_EXCEPTION_STACK_SIZE=0x800
OSZ_CFG_DRIVERS=1
OSZ_CFG_UART=1
OSZ_CFG_TIMER=1
OSZ_CFG_TEST_SUITE=1
OSZ_CFG_TARGETS=1
OSZ_CFG_PLATFORM=qemu_virt
OSZ_CFG_SHELL=1

)