CONFIG_CURRENT_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CONFIG_CURRENT_DIR := $(dir $(CONFIG_CURRENT_PATH))
CONFIG_MODULE := mem

LOCAL_$(CONFIG_MODULE)_INCLUDE :=
ifeq ($(OSZ_CFG_MEM), y)

LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/include

ifeq ($(OSZ_CFG_BESTFIT), y)
LOCAL_$(CONFIG_MODULE)_INCLUDE += -I$(CONFIG_CURRENT_DIR)/bestfit/include
endif

endif